baseurl = "https://gulugulufm.github.io/"
languageCode = "zh-cn"
title = "闭门造车"
theme = "hugo-cards"
paginate = 12
googleAnalytics = "UA-176054859-1"

[params]
  author = "Miki Hau"
  description = "《闭门造车》是一档关于创作者、创作故事和创作体验的访谈播客。这里有Miki和各类创作者的深度访谈，讲述创作背后的故事。"
  defaultImage = "gulugulu.jpg"
  Tagline = "听到创作背后的故事"

  twitterHandle = "@gulugulufm"
  twitter = "https://twitter.com/gulugulufm"
  github = "https://github.com/gulugulufm"
  email = "gulugulufm@gmail.com"
  substack = "https://gulugulufm.substack.com/p/coming-soon"
  weibo = "https://weibo.com/p/1005057361235474/"
  douban = "https://www.douban.com/people/49489567/"
  telegram = "https://t.me/gulugulufm"
  mastodon = "https://m.cmx.im/@mikihau"

  rss = "https://anchor.fm/s/2d9522d4/podcast/rss"
  apple = "https://podcasts.apple.com/us/podcast/id1525084596"
  apple_cn = "https://podcasts.apple.com/cn/podcast/id1525544698"
  spotify = "https://open.spotify.com/show/4FuOWZhWPvQXas4nMfdi4b"
  ximalaya = "https://www.ximalaya.com/gerenchengzhang/40308087/321222819"
  xiaoyuzhou = "https://www.xiaoyuzhoufm.com/podcast/5f1c6bbf9504bbdb771f8fd9"
  overcast = "https://overcast.fm/itunes1525084596"
  google = "https://www.google.com/podcasts?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy8yZDk1MjJkNC9wb2RjYXN0L3Jzcw"
  breaker = "https://www.breaker.audio/bi-men-zao-che"
  pocketcast = "https://pca.st/pdognhfd"
  moonfm = "https://moon.fm/podcasts/724297"

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  [params.copyright]
     name = "Miki Hau"
     link = "https://www.douban.com/people/49489567/"
     license_url = "https://creativecommons.org/licenses/by-nd/4.0/deed.zh"
     license_name = "CC BY-ND 4.0"
     host_name = "Github Pages"
     host_url = "https://pages.github.com/"
